on:
  workflow_dispatch:
env:
  FOLDER: /opt/imc/imc-ms
  IMAGE: imc-ms
  VERSION: latest
jobs:
  create-folder:
    name: create folder
    runs-on: ubuntu-latest
    steps:
      - name: run step create folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo mkdir -p ${{env.FOLDER}}
            sudo ls -al ${{env.FOLDER}}
      
      - name: clone repository
        uses: actions/checkout@v4
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: ".env,compose.yaml"
          target: ${{env.FOLDER}}